### ISSUE TITLE
部署成功后无法生效

### ISSUE THREAD

**Issue by weiyouwozuiku** [Lbingyi/HerokuXray#1]
站点部署为：https://studygo.herokuapp.com/
UUID使用的默认UUID，即24b4b1e1-7a89-45f6-858c-242cf53b5bdb
vmess链接为：vmess://eyJhZGQiOiJzdHVkeWdvLmhlcm9rdWFwcC5jb20iLCJhaWQiOjAsImhvc3QiOiJoZXJva3UuNTIwMDMwNy54eXoiLCJpZCI6IjI0YjRiMWUxLTdhODktNDVmNi04NThjLTI0MmNmNTNiNWJkYiIsIm5ldCI6IndzIiwicGF0aCI6Ii8yNGI0YjFlMS03YTg5LTQ1ZjYtODU4Yy0yNDJjZjUzYjViZGItdm1lc3MiLCJwb3J0Ijo0NDMsInBzIjoiaGVyb2t1X3N0dWR5Z28uaGVyb2t1YXBwLmNvbTo0NDMiLCJ0bHMiOiJ0bHMiLCJ0eXBlIjoibm9uZSIsInYiOjJ9

报错信息为：
[Warning] [3699847088] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:38 [Warning] [1518461813] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:38 [Warning] [3939584320] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:39 [Warning] [3596927692] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:39 [Warning] [642344612] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:40 [Warning] [2468415736] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:42 [Warning] [4155083276] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:42 [Warning] [3189210089] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://studygo.herokuapp.com/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vmess):  > x509: certificate is valid for *.herokuapp.com, herokuapp.com, not heroku.5200307.xyz] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/10 11:30:42 [W

**Comment by Lbingyi** [comment]
host 删掉 heroku.5200307.xyz

**Comment by weiyouwozuiku** [comment]
您好 ，我删除host后还是无法成功，另外我做了cf反代，地址是https://heroku.bpan.workers.dev/，请问需要如何修改。或者您能给一个生效的vmess链接去掉地址制类的信息么，我觉得我哪里出错了，但是没检查出来。万分感谢。

**Comment by Lbingyi** [comment]
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogImhlcm9rdV9zdHVkeWdvLmhlcm9rdWFwcC5jb206NDQzIiwNCiAgImFkZCI6ICIxMDQuMjQuMjYuMTE2IiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogIjI0YjRiMWUxLTdhODktNDVmNi04NThjLTI0MmNmNTNiNWJkYiIsDQogICJhaWQiOiAiMCIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiaGVyb2t1LmJwYW4ud29ya2Vycy5kZXYiLA0KICAicGF0aCI6ICIvMjRiNGIxZTEtN2E4OS00NWY2LTg1OGMtMjQyY2Y1M2I1YmRiLXZtZXNzIiwNCiAgInRscyI6ICJ0bHMiLA0KICAic25pIjogIiINCn0=

**Comment by weiyouwozuiku** [comment]
地址需要填写的是cf的ip么，谢谢了

**Comment by Lbingyi** [comment]
对的填写CF优选出来的IP

**Comment by weiyouwozuiku** [comment]
懂了，感谢。
